// Code generated by "enumer -type=ItemAssetType -trimprefix=ItemAssetType"; DO NOT EDIT.

package types

import (
	"fmt"
	"strings"
)

const _ItemAssetTypeName = "ImageTShirtAudioMeshLuaHatPlaceModelShirtPantsDecalHeadFaceGearBadgeAnimationTorsoRightArmLeftArmLeftLegRightLegPackageGamePassPluginMeshPartHairAccessoryFaceAccessoryNeckAccessoryShoulderAccessoryFrontAccessoryBackAccessoryWaistAccessoryClimbAnimationDeathAnimationFallAnimationIdleAnimationJumpAnimationRunAnimationSwimAnimationWalkAnimationPoseAnimationEarAccessoryEyeAccessoryEmoteAnimationVideoTShirtAccessoryShirtAccessoryPantsAccessoryJacketAccessorySweaterAccessoryShortsAccessoryLeftShoeAccessoryRightShoeAccessoryDressSkirtAccessoryFontFamilyEyebrowAccessoryEyelashAccessoryMoodAnimationDynamicHead"
const _ItemAssetTypeLowerName = "imagetshirtaudiomeshluahatplacemodelshirtpantsdecalheadfacegearbadgeanimationtorsorightarmleftarmleftlegrightlegpackagegamepasspluginmeshparthairaccessoryfaceaccessoryneckaccessoryshoulderaccessoryfrontaccessorybackaccessorywaistaccessoryclimbanimationdeathanimationfallanimationidleanimationjumpanimationrunanimationswimanimationwalkanimationposeanimationearaccessoryeyeaccessoryemoteanimationvideotshirtaccessoryshirtaccessorypantsaccessoryjacketaccessorysweateraccessoryshortsaccessoryleftshoeaccessoryrightshoeaccessorydressskirtaccessoryfontfamilyeyebrowaccessoryeyelashaccessorymoodanimationdynamichead"

var _ItemAssetTypeMap = map[ItemAssetType]string{
	1:  _ItemAssetTypeName[0:5],
	2:  _ItemAssetTypeName[5:11],
	3:  _ItemAssetTypeName[11:16],
	4:  _ItemAssetTypeName[16:20],
	5:  _ItemAssetTypeName[20:23],
	8:  _ItemAssetTypeName[23:26],
	9:  _ItemAssetTypeName[26:31],
	10: _ItemAssetTypeName[31:36],
	11: _ItemAssetTypeName[36:41],
	12: _ItemAssetTypeName[41:46],
	13: _ItemAssetTypeName[46:51],
	17: _ItemAssetTypeName[51:55],
	18: _ItemAssetTypeName[55:59],
	19: _ItemAssetTypeName[59:63],
	21: _ItemAssetTypeName[63:68],
	24: _ItemAssetTypeName[68:77],
	27: _ItemAssetTypeName[77:82],
	28: _ItemAssetTypeName[82:90],
	29: _ItemAssetTypeName[90:97],
	30: _ItemAssetTypeName[97:104],
	31: _ItemAssetTypeName[104:112],
	32: _ItemAssetTypeName[112:119],
	34: _ItemAssetTypeName[119:127],
	38: _ItemAssetTypeName[127:133],
	40: _ItemAssetTypeName[133:141],
	41: _ItemAssetTypeName[141:154],
	42: _ItemAssetTypeName[154:167],
	43: _ItemAssetTypeName[167:180],
	44: _ItemAssetTypeName[180:197],
	45: _ItemAssetTypeName[197:211],
	46: _ItemAssetTypeName[211:224],
	47: _ItemAssetTypeName[224:238],
	48: _ItemAssetTypeName[238:252],
	49: _ItemAssetTypeName[252:266],
	50: _ItemAssetTypeName[266:279],
	51: _ItemAssetTypeName[279:292],
	52: _ItemAssetTypeName[292:305],
	53: _ItemAssetTypeName[305:317],
	54: _ItemAssetTypeName[317:330],
	55: _ItemAssetTypeName[330:343],
	56: _ItemAssetTypeName[343:356],
	57: _ItemAssetTypeName[356:368],
	58: _ItemAssetTypeName[368:380],
	61: _ItemAssetTypeName[380:394],
	62: _ItemAssetTypeName[394:399],
	64: _ItemAssetTypeName[399:414],
	65: _ItemAssetTypeName[414:428],
	66: _ItemAssetTypeName[428:442],
	67: _ItemAssetTypeName[442:457],
	68: _ItemAssetTypeName[457:473],
	69: _ItemAssetTypeName[473:488],
	70: _ItemAssetTypeName[488:505],
	71: _ItemAssetTypeName[505:523],
	72: _ItemAssetTypeName[523:542],
	73: _ItemAssetTypeName[542:552],
	76: _ItemAssetTypeName[552:568],
	77: _ItemAssetTypeName[568:584],
	78: _ItemAssetTypeName[584:597],
	79: _ItemAssetTypeName[597:608],
}

func (i ItemAssetType) String() string {
	if str, ok := _ItemAssetTypeMap[i]; ok {
		return str
	}
	return fmt.Sprintf("ItemAssetType(%d)", i)
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ItemAssetTypeNoOp() {
	var x [1]struct{}
	_ = x[ItemAssetTypeImage-(1)]
	_ = x[ItemAssetTypeTShirt-(2)]
	_ = x[ItemAssetTypeAudio-(3)]
	_ = x[ItemAssetTypeMesh-(4)]
	_ = x[ItemAssetTypeLua-(5)]
	_ = x[ItemAssetTypeHat-(8)]
	_ = x[ItemAssetTypePlace-(9)]
	_ = x[ItemAssetTypeModel-(10)]
	_ = x[ItemAssetTypeShirt-(11)]
	_ = x[ItemAssetTypePants-(12)]
	_ = x[ItemAssetTypeDecal-(13)]
	_ = x[ItemAssetTypeHead-(17)]
	_ = x[ItemAssetTypeFace-(18)]
	_ = x[ItemAssetTypeGear-(19)]
	_ = x[ItemAssetTypeBadge-(21)]
	_ = x[ItemAssetTypeAnimation-(24)]
	_ = x[ItemAssetTypeTorso-(27)]
	_ = x[ItemAssetTypeRightArm-(28)]
	_ = x[ItemAssetTypeLeftArm-(29)]
	_ = x[ItemAssetTypeLeftLeg-(30)]
	_ = x[ItemAssetTypeRightLeg-(31)]
	_ = x[ItemAssetTypePackage-(32)]
	_ = x[ItemAssetTypeGamePass-(34)]
	_ = x[ItemAssetTypePlugin-(38)]
	_ = x[ItemAssetTypeMeshPart-(40)]
	_ = x[ItemAssetTypeHairAccessory-(41)]
	_ = x[ItemAssetTypeFaceAccessory-(42)]
	_ = x[ItemAssetTypeNeckAccessory-(43)]
	_ = x[ItemAssetTypeShoulderAccessory-(44)]
	_ = x[ItemAssetTypeFrontAccessory-(45)]
	_ = x[ItemAssetTypeBackAccessory-(46)]
	_ = x[ItemAssetTypeWaistAccessory-(47)]
	_ = x[ItemAssetTypeClimbAnimation-(48)]
	_ = x[ItemAssetTypeDeathAnimation-(49)]
	_ = x[ItemAssetTypeFallAnimation-(50)]
	_ = x[ItemAssetTypeIdleAnimation-(51)]
	_ = x[ItemAssetTypeJumpAnimation-(52)]
	_ = x[ItemAssetTypeRunAnimation-(53)]
	_ = x[ItemAssetTypeSwimAnimation-(54)]
	_ = x[ItemAssetTypeWalkAnimation-(55)]
	_ = x[ItemAssetTypePoseAnimation-(56)]
	_ = x[ItemAssetTypeEarAccessory-(57)]
	_ = x[ItemAssetTypeEyeAccessory-(58)]
	_ = x[ItemAssetTypeEmoteAnimation-(61)]
	_ = x[ItemAssetTypeVideo-(62)]
	_ = x[ItemAssetTypeTShirtAccessory-(64)]
	_ = x[ItemAssetTypeShirtAccessory-(65)]
	_ = x[ItemAssetTypePantsAccessory-(66)]
	_ = x[ItemAssetTypeJacketAccessory-(67)]
	_ = x[ItemAssetTypeSweaterAccessory-(68)]
	_ = x[ItemAssetTypeShortsAccessory-(69)]
	_ = x[ItemAssetTypeLeftShoeAccessory-(70)]
	_ = x[ItemAssetTypeRightShoeAccessory-(71)]
	_ = x[ItemAssetTypeDressSkirtAccessory-(72)]
	_ = x[ItemAssetTypeFontFamily-(73)]
	_ = x[ItemAssetTypeEyebrowAccessory-(76)]
	_ = x[ItemAssetTypeEyelashAccessory-(77)]
	_ = x[ItemAssetTypeMoodAnimation-(78)]
	_ = x[ItemAssetTypeDynamicHead-(79)]
}

var _ItemAssetTypeValues = []ItemAssetType{ItemAssetTypeImage, ItemAssetTypeTShirt, ItemAssetTypeAudio, ItemAssetTypeMesh, ItemAssetTypeLua, ItemAssetTypeHat, ItemAssetTypePlace, ItemAssetTypeModel, ItemAssetTypeShirt, ItemAssetTypePants, ItemAssetTypeDecal, ItemAssetTypeHead, ItemAssetTypeFace, ItemAssetTypeGear, ItemAssetTypeBadge, ItemAssetTypeAnimation, ItemAssetTypeTorso, ItemAssetTypeRightArm, ItemAssetTypeLeftArm, ItemAssetTypeLeftLeg, ItemAssetTypeRightLeg, ItemAssetTypePackage, ItemAssetTypeGamePass, ItemAssetTypePlugin, ItemAssetTypeMeshPart, ItemAssetTypeHairAccessory, ItemAssetTypeFaceAccessory, ItemAssetTypeNeckAccessory, ItemAssetTypeShoulderAccessory, ItemAssetTypeFrontAccessory, ItemAssetTypeBackAccessory, ItemAssetTypeWaistAccessory, ItemAssetTypeClimbAnimation, ItemAssetTypeDeathAnimation, ItemAssetTypeFallAnimation, ItemAssetTypeIdleAnimation, ItemAssetTypeJumpAnimation, ItemAssetTypeRunAnimation, ItemAssetTypeSwimAnimation, ItemAssetTypeWalkAnimation, ItemAssetTypePoseAnimation, ItemAssetTypeEarAccessory, ItemAssetTypeEyeAccessory, ItemAssetTypeEmoteAnimation, ItemAssetTypeVideo, ItemAssetTypeTShirtAccessory, ItemAssetTypeShirtAccessory, ItemAssetTypePantsAccessory, ItemAssetTypeJacketAccessory, ItemAssetTypeSweaterAccessory, ItemAssetTypeShortsAccessory, ItemAssetTypeLeftShoeAccessory, ItemAssetTypeRightShoeAccessory, ItemAssetTypeDressSkirtAccessory, ItemAssetTypeFontFamily, ItemAssetTypeEyebrowAccessory, ItemAssetTypeEyelashAccessory, ItemAssetTypeMoodAnimation, ItemAssetTypeDynamicHead}

var _ItemAssetTypeNameToValueMap = map[string]ItemAssetType{
	_ItemAssetTypeName[0:5]:          ItemAssetTypeImage,
	_ItemAssetTypeLowerName[0:5]:     ItemAssetTypeImage,
	_ItemAssetTypeName[5:11]:         ItemAssetTypeTShirt,
	_ItemAssetTypeLowerName[5:11]:    ItemAssetTypeTShirt,
	_ItemAssetTypeName[11:16]:        ItemAssetTypeAudio,
	_ItemAssetTypeLowerName[11:16]:   ItemAssetTypeAudio,
	_ItemAssetTypeName[16:20]:        ItemAssetTypeMesh,
	_ItemAssetTypeLowerName[16:20]:   ItemAssetTypeMesh,
	_ItemAssetTypeName[20:23]:        ItemAssetTypeLua,
	_ItemAssetTypeLowerName[20:23]:   ItemAssetTypeLua,
	_ItemAssetTypeName[23:26]:        ItemAssetTypeHat,
	_ItemAssetTypeLowerName[23:26]:   ItemAssetTypeHat,
	_ItemAssetTypeName[26:31]:        ItemAssetTypePlace,
	_ItemAssetTypeLowerName[26:31]:   ItemAssetTypePlace,
	_ItemAssetTypeName[31:36]:        ItemAssetTypeModel,
	_ItemAssetTypeLowerName[31:36]:   ItemAssetTypeModel,
	_ItemAssetTypeName[36:41]:        ItemAssetTypeShirt,
	_ItemAssetTypeLowerName[36:41]:   ItemAssetTypeShirt,
	_ItemAssetTypeName[41:46]:        ItemAssetTypePants,
	_ItemAssetTypeLowerName[41:46]:   ItemAssetTypePants,
	_ItemAssetTypeName[46:51]:        ItemAssetTypeDecal,
	_ItemAssetTypeLowerName[46:51]:   ItemAssetTypeDecal,
	_ItemAssetTypeName[51:55]:        ItemAssetTypeHead,
	_ItemAssetTypeLowerName[51:55]:   ItemAssetTypeHead,
	_ItemAssetTypeName[55:59]:        ItemAssetTypeFace,
	_ItemAssetTypeLowerName[55:59]:   ItemAssetTypeFace,
	_ItemAssetTypeName[59:63]:        ItemAssetTypeGear,
	_ItemAssetTypeLowerName[59:63]:   ItemAssetTypeGear,
	_ItemAssetTypeName[63:68]:        ItemAssetTypeBadge,
	_ItemAssetTypeLowerName[63:68]:   ItemAssetTypeBadge,
	_ItemAssetTypeName[68:77]:        ItemAssetTypeAnimation,
	_ItemAssetTypeLowerName[68:77]:   ItemAssetTypeAnimation,
	_ItemAssetTypeName[77:82]:        ItemAssetTypeTorso,
	_ItemAssetTypeLowerName[77:82]:   ItemAssetTypeTorso,
	_ItemAssetTypeName[82:90]:        ItemAssetTypeRightArm,
	_ItemAssetTypeLowerName[82:90]:   ItemAssetTypeRightArm,
	_ItemAssetTypeName[90:97]:        ItemAssetTypeLeftArm,
	_ItemAssetTypeLowerName[90:97]:   ItemAssetTypeLeftArm,
	_ItemAssetTypeName[97:104]:       ItemAssetTypeLeftLeg,
	_ItemAssetTypeLowerName[97:104]:  ItemAssetTypeLeftLeg,
	_ItemAssetTypeName[104:112]:      ItemAssetTypeRightLeg,
	_ItemAssetTypeLowerName[104:112]: ItemAssetTypeRightLeg,
	_ItemAssetTypeName[112:119]:      ItemAssetTypePackage,
	_ItemAssetTypeLowerName[112:119]: ItemAssetTypePackage,
	_ItemAssetTypeName[119:127]:      ItemAssetTypeGamePass,
	_ItemAssetTypeLowerName[119:127]: ItemAssetTypeGamePass,
	_ItemAssetTypeName[127:133]:      ItemAssetTypePlugin,
	_ItemAssetTypeLowerName[127:133]: ItemAssetTypePlugin,
	_ItemAssetTypeName[133:141]:      ItemAssetTypeMeshPart,
	_ItemAssetTypeLowerName[133:141]: ItemAssetTypeMeshPart,
	_ItemAssetTypeName[141:154]:      ItemAssetTypeHairAccessory,
	_ItemAssetTypeLowerName[141:154]: ItemAssetTypeHairAccessory,
	_ItemAssetTypeName[154:167]:      ItemAssetTypeFaceAccessory,
	_ItemAssetTypeLowerName[154:167]: ItemAssetTypeFaceAccessory,
	_ItemAssetTypeName[167:180]:      ItemAssetTypeNeckAccessory,
	_ItemAssetTypeLowerName[167:180]: ItemAssetTypeNeckAccessory,
	_ItemAssetTypeName[180:197]:      ItemAssetTypeShoulderAccessory,
	_ItemAssetTypeLowerName[180:197]: ItemAssetTypeShoulderAccessory,
	_ItemAssetTypeName[197:211]:      ItemAssetTypeFrontAccessory,
	_ItemAssetTypeLowerName[197:211]: ItemAssetTypeFrontAccessory,
	_ItemAssetTypeName[211:224]:      ItemAssetTypeBackAccessory,
	_ItemAssetTypeLowerName[211:224]: ItemAssetTypeBackAccessory,
	_ItemAssetTypeName[224:238]:      ItemAssetTypeWaistAccessory,
	_ItemAssetTypeLowerName[224:238]: ItemAssetTypeWaistAccessory,
	_ItemAssetTypeName[238:252]:      ItemAssetTypeClimbAnimation,
	_ItemAssetTypeLowerName[238:252]: ItemAssetTypeClimbAnimation,
	_ItemAssetTypeName[252:266]:      ItemAssetTypeDeathAnimation,
	_ItemAssetTypeLowerName[252:266]: ItemAssetTypeDeathAnimation,
	_ItemAssetTypeName[266:279]:      ItemAssetTypeFallAnimation,
	_ItemAssetTypeLowerName[266:279]: ItemAssetTypeFallAnimation,
	_ItemAssetTypeName[279:292]:      ItemAssetTypeIdleAnimation,
	_ItemAssetTypeLowerName[279:292]: ItemAssetTypeIdleAnimation,
	_ItemAssetTypeName[292:305]:      ItemAssetTypeJumpAnimation,
	_ItemAssetTypeLowerName[292:305]: ItemAssetTypeJumpAnimation,
	_ItemAssetTypeName[305:317]:      ItemAssetTypeRunAnimation,
	_ItemAssetTypeLowerName[305:317]: ItemAssetTypeRunAnimation,
	_ItemAssetTypeName[317:330]:      ItemAssetTypeSwimAnimation,
	_ItemAssetTypeLowerName[317:330]: ItemAssetTypeSwimAnimation,
	_ItemAssetTypeName[330:343]:      ItemAssetTypeWalkAnimation,
	_ItemAssetTypeLowerName[330:343]: ItemAssetTypeWalkAnimation,
	_ItemAssetTypeName[343:356]:      ItemAssetTypePoseAnimation,
	_ItemAssetTypeLowerName[343:356]: ItemAssetTypePoseAnimation,
	_ItemAssetTypeName[356:368]:      ItemAssetTypeEarAccessory,
	_ItemAssetTypeLowerName[356:368]: ItemAssetTypeEarAccessory,
	_ItemAssetTypeName[368:380]:      ItemAssetTypeEyeAccessory,
	_ItemAssetTypeLowerName[368:380]: ItemAssetTypeEyeAccessory,
	_ItemAssetTypeName[380:394]:      ItemAssetTypeEmoteAnimation,
	_ItemAssetTypeLowerName[380:394]: ItemAssetTypeEmoteAnimation,
	_ItemAssetTypeName[394:399]:      ItemAssetTypeVideo,
	_ItemAssetTypeLowerName[394:399]: ItemAssetTypeVideo,
	_ItemAssetTypeName[399:414]:      ItemAssetTypeTShirtAccessory,
	_ItemAssetTypeLowerName[399:414]: ItemAssetTypeTShirtAccessory,
	_ItemAssetTypeName[414:428]:      ItemAssetTypeShirtAccessory,
	_ItemAssetTypeLowerName[414:428]: ItemAssetTypeShirtAccessory,
	_ItemAssetTypeName[428:442]:      ItemAssetTypePantsAccessory,
	_ItemAssetTypeLowerName[428:442]: ItemAssetTypePantsAccessory,
	_ItemAssetTypeName[442:457]:      ItemAssetTypeJacketAccessory,
	_ItemAssetTypeLowerName[442:457]: ItemAssetTypeJacketAccessory,
	_ItemAssetTypeName[457:473]:      ItemAssetTypeSweaterAccessory,
	_ItemAssetTypeLowerName[457:473]: ItemAssetTypeSweaterAccessory,
	_ItemAssetTypeName[473:488]:      ItemAssetTypeShortsAccessory,
	_ItemAssetTypeLowerName[473:488]: ItemAssetTypeShortsAccessory,
	_ItemAssetTypeName[488:505]:      ItemAssetTypeLeftShoeAccessory,
	_ItemAssetTypeLowerName[488:505]: ItemAssetTypeLeftShoeAccessory,
	_ItemAssetTypeName[505:523]:      ItemAssetTypeRightShoeAccessory,
	_ItemAssetTypeLowerName[505:523]: ItemAssetTypeRightShoeAccessory,
	_ItemAssetTypeName[523:542]:      ItemAssetTypeDressSkirtAccessory,
	_ItemAssetTypeLowerName[523:542]: ItemAssetTypeDressSkirtAccessory,
	_ItemAssetTypeName[542:552]:      ItemAssetTypeFontFamily,
	_ItemAssetTypeLowerName[542:552]: ItemAssetTypeFontFamily,
	_ItemAssetTypeName[552:568]:      ItemAssetTypeEyebrowAccessory,
	_ItemAssetTypeLowerName[552:568]: ItemAssetTypeEyebrowAccessory,
	_ItemAssetTypeName[568:584]:      ItemAssetTypeEyelashAccessory,
	_ItemAssetTypeLowerName[568:584]: ItemAssetTypeEyelashAccessory,
	_ItemAssetTypeName[584:597]:      ItemAssetTypeMoodAnimation,
	_ItemAssetTypeLowerName[584:597]: ItemAssetTypeMoodAnimation,
	_ItemAssetTypeName[597:608]:      ItemAssetTypeDynamicHead,
	_ItemAssetTypeLowerName[597:608]: ItemAssetTypeDynamicHead,
}

var _ItemAssetTypeNames = []string{
	_ItemAssetTypeName[0:5],
	_ItemAssetTypeName[5:11],
	_ItemAssetTypeName[11:16],
	_ItemAssetTypeName[16:20],
	_ItemAssetTypeName[20:23],
	_ItemAssetTypeName[23:26],
	_ItemAssetTypeName[26:31],
	_ItemAssetTypeName[31:36],
	_ItemAssetTypeName[36:41],
	_ItemAssetTypeName[41:46],
	_ItemAssetTypeName[46:51],
	_ItemAssetTypeName[51:55],
	_ItemAssetTypeName[55:59],
	_ItemAssetTypeName[59:63],
	_ItemAssetTypeName[63:68],
	_ItemAssetTypeName[68:77],
	_ItemAssetTypeName[77:82],
	_ItemAssetTypeName[82:90],
	_ItemAssetTypeName[90:97],
	_ItemAssetTypeName[97:104],
	_ItemAssetTypeName[104:112],
	_ItemAssetTypeName[112:119],
	_ItemAssetTypeName[119:127],
	_ItemAssetTypeName[127:133],
	_ItemAssetTypeName[133:141],
	_ItemAssetTypeName[141:154],
	_ItemAssetTypeName[154:167],
	_ItemAssetTypeName[167:180],
	_ItemAssetTypeName[180:197],
	_ItemAssetTypeName[197:211],
	_ItemAssetTypeName[211:224],
	_ItemAssetTypeName[224:238],
	_ItemAssetTypeName[238:252],
	_ItemAssetTypeName[252:266],
	_ItemAssetTypeName[266:279],
	_ItemAssetTypeName[279:292],
	_ItemAssetTypeName[292:305],
	_ItemAssetTypeName[305:317],
	_ItemAssetTypeName[317:330],
	_ItemAssetTypeName[330:343],
	_ItemAssetTypeName[343:356],
	_ItemAssetTypeName[356:368],
	_ItemAssetTypeName[368:380],
	_ItemAssetTypeName[380:394],
	_ItemAssetTypeName[394:399],
	_ItemAssetTypeName[399:414],
	_ItemAssetTypeName[414:428],
	_ItemAssetTypeName[428:442],
	_ItemAssetTypeName[442:457],
	_ItemAssetTypeName[457:473],
	_ItemAssetTypeName[473:488],
	_ItemAssetTypeName[488:505],
	_ItemAssetTypeName[505:523],
	_ItemAssetTypeName[523:542],
	_ItemAssetTypeName[542:552],
	_ItemAssetTypeName[552:568],
	_ItemAssetTypeName[568:584],
	_ItemAssetTypeName[584:597],
	_ItemAssetTypeName[597:608],
}

// ItemAssetTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ItemAssetTypeString(s string) (ItemAssetType, error) {
	if val, ok := _ItemAssetTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ItemAssetTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ItemAssetType values", s)
}

// ItemAssetTypeValues returns all values of the enum
func ItemAssetTypeValues() []ItemAssetType {
	return _ItemAssetTypeValues
}

// ItemAssetTypeStrings returns a slice of all String values of the enum
func ItemAssetTypeStrings() []string {
	strs := make([]string, len(_ItemAssetTypeNames))
	copy(strs, _ItemAssetTypeNames)
	return strs
}

// IsAItemAssetType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ItemAssetType) IsAItemAssetType() bool {
	_, ok := _ItemAssetTypeMap[i]
	return ok
}
